blacklight:
  image: itma.blacklight
  ports:
    - "3000:3000"
  links: 
    - solr

solr:
  image: itma.solr
  volumes:
    - ./solrconfig:/solrconfig
  command: solr-create -c blacklight -d /solrconfig
  ports:
    - "8983:8983"
  expose:
    - "8983"

