blacklight:
  image: itma/blacklight
  ports:
    - "3000:3000"
  links: 
    - solr
    - postgres

solr:
  image: itma/solr
  volumes:
    - ./solrconfig:/solrconfig
  command: solr-create -c blacklight -d /solrconfig
  ports:
    - "8983:8983"
  expose:
    - "8983"


postgres:
  image: postgres
  ports:
    - "5432"